# Generated by Django 5.0.1 on 2024-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInterface', '0002_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
